[package]
name = "tmd-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
tmd-core = { path = "../tmd-core" }
pulldown-cmark = "0.9"
base64 = "0.21"
html-escape = "0.2"
rusqlite = { version = "0.29", features = ["bundled"] }
